ConcertBooking.UI/Controllers/ArtistsController.cs
using ConcertBooking_Entities;
using ConcertBooking_Repository;
using ConcertBooking_Repository.Interfaces;
using ConcertBooking_UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ConcertBooking.UI.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ArtistsController : Controller
    {
        private readonly IArtistRepo _artistRepo;
        private readonly IUtilityRepo _utilityRepo;
        private string containerName = "ArtistImage";
        public ArtistsController(IArtistRepo artistRepo, IUtilityRepo utilityRepo)
        {
            _artistRepo = artistRepo;
            _utilityRepo = utilityRepo;
        }

        public async Task<IActionResult> Index()
        {
            List<ArtistViewModel> vm = new List<ArtistViewModel> ();
            var artists = await _artistRepo.GetAll();
            foreach(var artist in artists)
            {
                vm.Add(new ArtistViewModel
                {
                    Id = artist.Id,
                    Name = artist.Name,
                    Bio = artist.Bio,
                    ImageUrl = artist.ImageUrl,
                });
            }
            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateArtistViewModel vm)
        {
            var artist = new Artist
            {
                Name = vm.Name,
                Bio = vm.Bio,
            };
            if (vm.ImageUrl != null)
            {
                artist.ImageUrl = await _utilityRepo.SaveImage(containerName, vm.ImageUrl);
            }
            await _artistRepo.Save(artist);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var artist = await _artistRepo.GetById(id);
            EditArtistViewModel vm = new EditArtistViewModel()
            {
                Id = artist.Id,
                Name = artist.Name,
                Bio = artist.Bio,
                ImageUrl = artist.ImageUrl,
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditArtistViewModel vm)
        {
            var artist = await _artistRepo.GetById(vm.Id);
            artist.Name = vm.Name;
            artist.Bio = vm.Bio;
            
            if (vm.ChooseImage != null)
            {
                artist.ImageUrl = await _utilityRepo.EditImage(containerName, vm.ChooseImage, artist.ImageUrl);
            }
            await _artistRepo.Edit(artist);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var artist = await _artistRepo.GetById(id);
            await _artistRepo.RemoveData(artist);
            return RedirectToAction("Index");

        }
    }
}

ConcertBooking.UI/Controllers/ConcertsController.cs
using ConcertBooking_Entities;
using ConcertBooking_Repository;
using ConcertBooking_Repository.Interfaces;
using ConcertBooking_UI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ConcertBooking.UI.Controllers
{
    public class ConcertsController : Controller
    {
        // To transfer data from controller to view we use three:
        // ViewBag - make dynamic variable, used for single HTTP request
        // ViewData - key value pair, used for single HTTP request
        // TempData - key value pair, used for multiple HTTP request
        private readonly IConcertRepo _concertRepo;
        private readonly IVenueRepo _venueRepo;
        private readonly IArtistRepo _artistRepo;
        private readonly IUtilityRepo _utilityRepo;
        private readonly IBookingRepo _bookingRepo;

        private string containerName = "ConcertImage";

        private string GetUserNameWithoutDomain(string email)
        {
            int atIndex = email.IndexOf('@'); // Find the index of '@' symbol
            if (atIndex != -1)
            {
                return email.Substring(0, atIndex); // If '@' symbol found, return the substring before '@'
            }
            else
            {
                return email; // If '@' symbol not found, return the original email
            }
        }

        public ConcertsController(IConcertRepo concertRepo, IVenueRepo venueRepo, IArtistRepo artistRepo, IUtilityRepo utilityRepo, IBookingRepo bookingRepo)
        {
            _concertRepo = concertRepo;
            _venueRepo = venueRepo;
            _artistRepo = artistRepo;
            _utilityRepo = utilityRepo;
            _bookingRepo = bookingRepo;
        }

        public async Task<IActionResult> Index()
        {
            List<ConcertViewModel> vm = new List<ConcertViewModel>();
            var concerts = await _concertRepo.GetAll();
            foreach (var concert in concerts)
            {
                vm.Add(new ConcertViewModel
                {
                    Id= concert.Id,
                    Name = concert.Name,
                    DateTime = concert.DateTime,
                    VenueName = concert.Venue.Name,
                    ArtistName = concert.Artist.Name
                });
            }
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var artists = await _artistRepo.GetAll();
            var venues = await _venueRepo.GetAll();
            ViewBag.artistList = new SelectList(artists, "Id", "Name");
            ViewBag.venueList = new SelectList(venues, "Id", "Name");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateConcertViewModel vm)
        {
            var concert = new Concert
            {
                Name = vm.Name,
                Description = vm.Description,
                DateTime = vm.DateTime,
                VenueId = vm.VenueId,
                ArtistId = vm.ArtistId,
            };
            if(vm.ImageUrl != null)
            {
                concert.ImageUrl = await _utilityRepo.SaveImage(containerName, vm.ImageUrl);
            }
            await _concertRepo.Save(concert);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var concert = await _concertRepo.GetById(id);
            var artists = await _artistRepo.GetAll();
            var venues = await _venueRepo.GetAll();
            ViewBag.artistList = new SelectList(artists, "Id", "Name");
            ViewBag.venueList = new SelectList(venues, "Id", "Name");

            EditConcertViewModel vm = new EditConcertViewModel()
            {
                Id=concert.Id,
                Name = concert.Name,
                Description = concert.Description,
                DateTime = concert.DateTime,
                ImageUrl = concert.ImageUrl,
                VenueId = concert.VenueId,
                ArtistId = concert.ArtistId,
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditConcertViewModel vm)
        {
            var concert = await _concertRepo.GetById(vm.Id);
            concert.Id = vm.Id;
            concert.Name = vm.Name;
            concert.Description = vm.Description;
            concert.DateTime = vm.DateTime;
            concert.ArtistId = vm.ArtistId;
            concert.VenueId = vm.VenueId;

            if(vm.ChooseImage != null)
            {
                concert.ImageUrl = await _utilityRepo.EditImage(containerName, vm.ChooseImage, concert.ImageUrl);
            }
            await _concertRepo.Edit(concert);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var state = await _concertRepo.GetById(id);
            await _concertRepo.RemoveData(state);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetTickets(int id)
        {
            var bookings = await _bookingRepo.GetAll(id);
            var vm = bookings.Select(a => new DashboadViewModel
            {
                UserName = GetUserNameWithoutDomain(a.User.UserName),
                ConcertName = a.Concert.Name,
                SeatNumber = string.Join(",", a.Tickets.Select(t=>t.SeatNumber))
            }).ToList();
            return View(vm);
        }
    }
}

ConcertBooking.UI/Controllers/TicketsController.cs
using ConcertBooking_Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using ConcertBooking_UI.ViewModels.TicketBookingViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ConcertBooking_UI.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ITicketRepo _ticketRepo;

        public TicketsController(ITicketRepo ticketRepo)
        {
            _ticketRepo = ticketRepo;
        }

        [Authorize]
        public async Task<IActionResult> MyTickets()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userId = claim.Value;

            var bookings = await _ticketRepo.GetBookings(userId);

            List<BookingViewModel> vm = new List<BookingViewModel>();
            foreach (var booking in bookings)
            {
                vm.Add(new BookingViewModel
                {
                    BookingId = booking.BookingId,
                    BookingDate = booking.BookingDate,
                    ConcertName = booking.Concert.Name,
                    Tickets = booking.Tickets.Select(ticketVM => new TicketViewModel
                    {
                        SeatNumber = ticketVM.SeatNumber
                    }).ToList()
                }); 
            }
            return View(vm);
        }
    }
}

ConcertBooking.UI/Controllers/VenuesController.cs
using ConcertBooking_Entities;
using ConcertBooking_Repository.Interfaces;
using ConcertBooking_UI.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ConcertBooking.UI.Controllers
{
    public class VenuesController : Controller
    {
        private readonly IVenueRepo _venueRepo;

        public VenuesController(IVenueRepo venueRepo)
        {
            _venueRepo = venueRepo;
        }

        public async Task<IActionResult> Index()
        {
            List<VenueViewModel> vm = new List<VenueViewModel>();
            var venues = await _venueRepo.GetAll();
            foreach (var venue in venues)
            {
                vm.Add(new VenueViewModel
                {
                    Id = venue.Id,
                    Name = venue.Name,
                    Address = venue.Address,
                    SeatCapacity = venue.SeatCapacity,
                });
            }
            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateVenueViewModel vm)
        {
            var venue = new Venue
            {
                Name = vm.Name,
                Address = vm.Address,
                SeatCapacity = vm.SeatCapacity,
            };
            await _venueRepo.Save(venue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var venue = await _venueRepo.GetById(id);
            VenueViewModel vm = new VenueViewModel()
            {
                Id = venue.Id,
                Name = venue.Name,
                Address = venue.Address,
                SeatCapacity= venue.SeatCapacity,
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(VenueViewModel vm)
        {
            var venue = new Venue
            {
                Id = vm.Id,
                Name = vm.Name,
                Address = vm.Address,
                SeatCapacity= vm.SeatCapacity,
            };
            await _venueRepo.Edit(venue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var venue = await _venueRepo.GetById(id);
            await _venueRepo.RemoveData(venue);
            return RedirectToAction("Index");

        }
    }
}

ConcertBooking.UI/Views/Shared/_Footer.cshtml
<footer class="border-top footer bg-secondary text-muted">
    <div class="text-center text-white mt-1">
        Made with <i class="bi bi-arrow-through-heart-fill"></i> by DevCcr
    </div>
</footer>

ConcertBooking.UI/Views/Shared/_HeaderNav.cshtml
@using ConcertBooking_Infrastructure

<nav class="navbar navbar-expand-lg bg-dark fixed-top" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fbrandslogos.com%2Fwp-content%2Fuploads%2Fimages%2Flarge%2Fconcert-logo.png&f=1&nofb=1&ipt=9b665694e5f178fe1d908168087c1858ae5154899d5c7dc4bf941f4766c1a0bc&ipo=images" width="150" height="40" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Index">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>

                @if (User.IsInRole(GlobalConfiguration.Admin_Role))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Venues" asp-action="Index">Venues</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Artists" asp-action="Index">Artists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Concerts" asp-action="Index">Concerts</a>
                    </li>
                }
                @* <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
                </div>
                </li> *@
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Tickets" asp-action="MyTickets">Tickets</a>
                    </li>
                }

            </ul>

            <partial name="_LoginPartial" />
            @* <form class="d-flex">
            <input class="form-control me-sm-2" type="search" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form> *@
        </div>
    </div>
</nav>

ConcertBooking.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConcertBooking.UI</title>
    <link rel="stylesheet" href="~/css/solar.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConcertBooking.UI.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <partial name="_HeaderNav" />
    </header>

    <div class="container">
        <main role="main" class="pb-3" id="content">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>